version: '3.8'

services:
  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/db-hml
      DB_USER: postgres
      DB_PASS: postgres
      DB_SHOW_SQL: true
      DB_DEBUG: DEBUG
      DB_TRACE: TRACE
      SERVER_PORT: 8081
      allow-origin: http://localhost:3000
      config.origin-permitida: http://localhost:3000
    restart: unless-stopped
    